name: weather_whenever
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.1.10
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  auto_route: ^5.0.4
  intl: ^0.17.0
  flutter_hooks: ^0.18.6
  dio: ^5.0.2
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.1
  get_it: ^7.2.0
  dartz: ^0.10.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  # flutter_intl:
  #   enabled: true

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400

